# Generated by Django 2.2.5 on 2020-09-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=5)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('idx', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('stock', models.IntegerField(blank=True, default=None, null=True)),
                ('sufficient', models.BooleanField(default=True)),
            ],
        ),
    ]
