# Generated by Django 3.1.2 on 2020-11-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_person_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
    ]
