# Generated by Django 2.2.5 on 2020-09-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calfit', '0010_auto_20190212_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
